Install `nginx-prometheus-exporter`  and export metrics over `cos`
charmed-kubernetes/charm-kubeapi-load-balancer pull request #30
Opened 2023-08-30 18:37 UTC by addyess

2023-08-31 13:47 UTC, mateoflorido requested changes
LGTM. Just one last thing, we have to change the `nginx_rule.yaml` file to check the `nginx_up` metric instead of the systemd service status.

2023-08-31 13:47 UTC, mateoflorido commented on src/charm.py
> +            TEMPLATES_PATH / "apilb.conf",
Ugh, nice catch 🎣

2023-08-31 13:58 UTC, addyess commented
> LGTM. Just one last thing, we have to change the `nginx_rule.yaml` file to check the `nginx_up` metric instead of the systemd service status.

I'm going to relate today to cos and see how things look in prometheus/grafana etc...

2023-09-01 11:56 UTC, mateoflorido approved these changes
LGTM!

2023-09-01 11:56 UTC, mateoflorido commented on tests/unit/test_charm.py
> +                Path.cwd() / "templates" / "apilb.conf",
```suggestion
                TEMPLATES_PATH / "apilb.conf",
```

2023-09-05 20:43 UTC, merged